name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        java: [11, 8]
        platform: [JVM, JS]
        exclude:
          - platform: JS
            java: 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v2
      - run: sbt +tests${{ matrix.platform }}/test
  native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v2
      - run: ./bin/native_setup.sh
      - run: sbt +testsNative/test
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v2
      - run: sbt +testsJVM/test
  scalajs06:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v2
      - run: sbt +testsJS/test
        env:
          SCALAJS_VERSION: "0.6.31"
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v2
      - run: ./bin/scalafmt --check
      - run: sbt scalafixAll
      - run: sbt docs/docusaurusCreateSite
