name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  jvm:
    strategy:
      fail-fast: false
      matrix:
        java: [11, 8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v2
      - run: sbt +testsJVM/test
  js:
    strategy:
      fail-fast: false
      matrix:
        scalajs: ["1.0.0-RC2", "0.6.31"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v2
      - run: sbt +testsJS/test
        env:
          SCALAJS_VERSION: ${{ matrix.scalajs }}
  native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v2
      - run: sbt +testsNative/test
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v2
      - run: sbt +testsJVM/test
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v2
      - run: ./bin/scalafmt --check
      - run: sbt scalafixAll
      - run: sbt docs/docusaurusCreateSite
